---
- name: Proxmox Unbuntu + Docker Clone deployment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Generate unique VM name
      set_fact:
        unique_name: "Ansible-test-{{ lookup('pipe', 'date +%H%M%S') }}"

    - name: Start to Clone VM
      community.proxmox.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
        validate_certs: false
        node: node01
        target: "{{ target_node }}"
        vmid: 100
        clone: ubuntu-26.04-docker-cloudinit-template
        name: "{{ unique_name }}"
        state: present
      register: new_vm_data

    - name: Cloudin Initialisierung
      community.proxmox.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
        validate_certs: false
        node: node02
        vmid: "{{new_vm_data.vmid}}"
        update: true
        ciuser: root
        cipassword: 123
        sshkeys: |
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG2RKn22zxdVaBENrVZTFtC1CYOMWZKQmQ4r6TJBtPzq khalil@Mac-mini-von-Khalil.local          
        ipconfig: 
          ipconfig0: "ip=dhcp"
        state: present

    - name: Einschalten
      community.proxmox.proxmox_kvm:
        api_host: "{{ lookup('env', 'PROXMOX_HOST') }}"
        api_user: "{{ lookup('env', 'PROXMOX_USER') }}"
        api_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
        validate_certs: false
        node: node02
        vmid: "{{ new_vm_data.vmid }}"
        state: started
    
            
    - name: Step 4 - Wait for VM to boot and get IP
      pause:
        seconds: 35

    - name: rescan Proxmox inventory
      meta: refresh_inventory

- name: Start to deploy Docker and Nginx
  hosts: "{{ hostvars['localhost']['unique_name'] }}"
  become: yes
  gather_facts: false
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no' 

  tasks:
    - name: Wait for SSH to be fully ready
      wait_for_connection:
        delay: 10
        sleep: 10
        timeout: 600

    - name: Gather facts manually after SSH is up
      setup:
    
    - name: Waiting for end of cloud-init
      ansible.builtin.command: cloud-init status --wait
      register: cloud_init_result
      changed_when: false
      failed_when: cloud_init_result.rc not in [0, 2]

    # 2. Устанавливаем pip3
    - name: instalationof pip3
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes
        
    
    - name: instalation of docker and others bib
      ansible.builtin.pip:
        name:
          - requests==2.31.0
          - docker>=7.1.0
        state: present
        executable: pip3
        extra_args: --break-system-packages --ignore-installed
    
    - name: Run Nginx container
      community.docker.docker_container:
        name: my-nginx
        image: nginx:latest
        state: started
        published_ports:
          - "80:80"